version: '3'
services:
    jupyter:
        image: varadtupe/nltk_jupyter:latest
        volumes:
            - ./data:/data
        ports:
            - 8899:8899
        networks:
            - VST
        command: jupyter notebook --port=8899 --no-browser --ip=0.0.0.0 --allow-root
networks:
      VST:
